import { Knex } from "knex";

export async function seed(knex: Knex) {
  const usersSeedData = [
    { username: "Mykhailo", bio: "-" },
    { username: "Rain", bio: "Chief Random Obsession Officer" },
    { username: "Alice", bio: "Coffee enthusiast" },
    { username: "Bob", bio: "Tech lover" },
    { username: "Charlie", bio: "Travel addict" },
    { username: "Diana", bio: "Foodie at heart" },
    { username: "Ethan", bio: "Gamer and streamer" },
    { username: "Fiona", bio: "Bookworm" },
    { username: "George", bio: "Nature lover" },
    { username: "Hannah", bio: "Fitness fanatic" },
    { username: "Ian", bio: "Music producer" },
    { username: "Julia", bio: "Art creator" },
    { username: "Kevin", bio: "History buff" },
    { username: "Liam", bio: "Car enthusiast" },
    { username: "Mia", bio: "Fashion blogger" },
  ];

  const postsSeedData = [
    {
      text: "Batman vs Superman is a 10/10 movie",
      hashtags: "opinion, movies",
      user_id: 1,
    },
    {
      text: "Tallinn is the Estonian New-York",
      hashtags: "cities",
      user_id: 1,
    },
    { text: "Lenovo > Apple", hashtags: "opinion", user_id: 2 },
    { text: "Coffee makes everything better!", hashtags: "coffee", user_id: 3 },
    { text: "Can't wait for the next tech conference!", hashtags: "tech", user_id: 4 },
    { text: "Traveling to Japan next month!", hashtags: "travel", user_id: 5 },
    { text: "Tried a new recipe today, it was amazing!", hashtags: "food", user_id: 6 },
    { text: "Just hit my streaming goal!", hashtags: "gaming", user_id: 7 },
    { text: "Just finished a great book!", hashtags: "books", user_id: 8 },
    { text: "Nature hikes are the best way to relax.", hashtags: "nature", user_id: 9 },
    { text: "Just completed a marathon!", hashtags: "fitness", user_id: 10 },
    { text: "Working on my next track!", hashtags: "music", user_id: 11 },
    { text: "Visited the Louvre last summer!", hashtags: "art", user_id: 12 },
    { text: "Did you know the Great Wall is over 13,000 miles long?", hashtags: "history", user_id: 13 },
    { text: "Just got my dream car!", hashtags: "cars", user_id: 14 },
    { text: "Fashion trends are so exciting right now!", hashtags: "fashion", user_id: 15 },
    { text: "Just discovered a hidden gem in the city!", hashtags: "cities", user_id: 1 },
    { text: "Can't wait for the next MCU movie!", hashtags: "movies", user_id: 2 },
    { text: "Trying out a new coffee place this weekend.", hashtags: "coffee", user_id: 3 },
    { text: "Exploring the mountains this weekend!", hashtags: "travel", user_id: 5 },
    { text: "Had a great game night with friends.", hashtags: "gaming", user_id: 7 },
    { text: "Just started a new novel, it's gripping!", hashtags: "books", user_id: 8 },
    { text: "Planting flowers in my garden this spring.", hashtags: "nature", user_id: 9 },
    { text: "Just got back from a yoga retreat!", hashtags: "fitness", user_id: 10 },
    { text: "Working on a new album!", hashtags: "music", user_id: 11 },
    { text: "Just painted a new piece!", hashtags: "art", user_id: 12 },
    { text: "Visited ancient ruins during my last trip.", hashtags: "history", user_id: 13 },
    { text: "Dreaming of my next car upgrade.", hashtags: "cars", user_id: 14 },
    { text: "Excited for the upcoming fashion show!", hashtags: "fashion", user_id: 15 },
    { text: "Exploring local cafes is my favorite hobby.", hashtags: "coffee", user_id: 3 },
    { text: "Attending a tech meetup this week!", hashtags: "tech", user_id: 4 },
    { text: "The world is full of amazing places to see.", hashtags: "travel", user_id: 5 },
    { text: "Just got a new gaming console!", hashtags: "gaming", user_id: 7 },
    { text: "A cozy night with a good book is all I need.", hashtags: "books", user_id: 8 },
    { text: "Nature walks are my therapy.", hashtags: "nature", user_id: 9 },
    { text: "Fitness goals are getting closer!", hashtags: "fitness", user_id: 10 },
    { text: "Collaborating with another artist soon!", hashtags: "music", user_id: 11 },
    { text: "So inspired by the art community!", hashtags: "art", user_id: 12 },
    { text: "History always fascinates me.", hashtags: "history", user_id: 13 },
    { text: "Always searching for the perfect ride.", hashtags: "cars", user_id: 14 },
    { text: "Creating content for my fashion blog!", hashtags: "fashion", user_id: 15 },
  ];

  await knex("users").insert(usersSeedData);
  await knex("posts").insert(postsSeedData);
}
